In [83]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# Random seed
random.seed(42)
np.random.seed(42)

# Number of Records
num_records = 5000

# Lists
states = ["Delhi", "Maharashtra", "Karnataka", "Bihar", "Gujarat", "Madhya Pradesh"]

cities = {
    "Delhi": ["New Delhi"],
    "Maharashtra": ["Mumbai", "Pune", "Nagpur"],
    "Karnataka": ["Bengaluru", "Mysuru"],
    "Bihar": ["Patna", "Darbhanga"],
    "Gujarat": ["Ahmedabad", "Surat"],
    "Madhya Pradesh": ["Indore", "Bhopal"]
}

regions = {
    "Delhi": "North",
    "Maharashtra": "West",
    "Karnataka": "South",
    "Bihar": "East",
    "Gujarat": "West",
    "Madhya Pradesh": "Central"
}

segments = ["Consumer", "Corporate", "Home Office"]

categories = {
    "Furniture": ["Chair", "Table", "Sofa", "Bookcase"],
    "Technology": ["Laptop", "Printer", "Keyboard", "Mouse"],
    "Office Supplies": ["Notebook", "Pen", "Paper", "Marker"]
}

payment_modes = ["Cash", "UPI", "Credit Card", "Debit Card", "Net Banking"]

ship_modes = ["Standard Class", "Second Class", "First Class", "Same Day"]

customer_names = [
    "Rahul","Amit","Neha","Priya","Ankit","Rohan","Sneha",
    "Pooja","Karan","Anjali","Vikas","Nisha","Saurabh",
    "Ritika","Arjun","Riya","Deepak","Shweta","Akash","Simran"
]

# Start Date
start_date = datetime(2023, 1, 1)

data = []

for i in range(1, num_records + 1):

    state = random.choice(states)
    city = random.choice(cities[state])

    category = random.choice(list(categories.keys()))
    sub_category = random.choice(categories[category])

    sales = round(np.random.uniform(200, 10000), 2)
    quantity = random.randint(1, 10)
    discount = random.choice([0, 5, 10, 15, 20])

    profit = round(sales * np.random.uniform(-0.05, 0.30), 2)

    order_date = start_date + timedelta(days=random.randint(0, 730))
    ship_date = order_date + timedelta(days=random.randint(1, 7))

   # Calculate Delivery Days
    delivery_days = (ship_date - order_date).days

# Calculate Profit Margin
    profit_margin = round((profit / sales) * 100, 2)

    data.append({
    "Order_ID": f"ORD{i:05d}",
    "Order_Date": order_date.strftime("%Y-%m-%d"),
    "Ship_Date": ship_date.strftime("%Y-%m-%d"),

    "Year": order_date.year,
    "Month": order_date.strftime("%B"),
    "Quarter": f"Q{((order_date.month-1)//3)+1}",

    "Customer_ID": f"CUST{random.randint(1001,9999)}",
    "Customer_Name": random.choice(customer_names),
    "Segment": random.choice(segments),
    "Country": "India",
    "State": state,
    "City": city,
    "Region": regions[state],
    "Category": category,
    "Sub_Category": sub_category,
    "Product_Name": sub_category,

    "Sales": sales,
    "Quantity": quantity,
    "Discount": discount,
    "Profit": profit,

    "Delivery_Days": delivery_days,
    "Profit_Margin": profit_margin,

    "Payment_Mode": random.choice(payment_modes),
    "Ship_Mode": random.choice(ship_modes)
})
# Create DataFrame
df = pd.DataFrame(data)

# Save CSV
df.to_csv("sales.csv", index=False)

print("sales.csv created successfully!")
print(df.head())
print("\nTotal Rows:", len(df))

sales.csv created successfully!
   Order_ID  Order_Date   Ship_Date  Year      Month Quarter Customer_ID  \
0  ORD00001  2023-05-23  2023-05-29  2023        May      Q2    CUST2680
1  ORD00002  2024-09-08  2024-09-09  2024  September      Q3    CUST4258
2  ORD00003  2023-10-12  2023-10-14  2023    October      Q4    CUST4528
3  ORD00004  2024-07-03  2024-07-04  2024       July      Q3    CUST7202
4  ORD00005  2023-10-24  2023-10-25  2023    October      Q4    CUST4815

  Customer_Name      Segment Country  ... Sub_Category Product_Name    Sales  \
0        Shweta     Consumer   India  ...         Sofa         Sofa  3870.49
1        Shweta    Corporate   India  ...        Table        Table  7373.54
2         Vikas     Consumer   India  ...        Table        Table  1728.98
3          Neha  Home Office   India  ...     Keyboard     Keyboard   769.22
4         Priya    Corporate   India  ...     Notebook     Notebook  6090.93

  Quantity Discount   Profit  Delivery_Days  Profit_Margin  Payment_Mode  \
0        4        5  1094.38              6          28.27   Net Banking
1        4       20  1176.30              1          15.95           UPI
2        7       10     7.95              2           0.46          Cash
3        1       15   194.74              1          25.32   Credit Card
4        1        5  1204.94              1          19.78   Credit Card

     Ship_Mode
0     Same Day
1     Same Day
2     Same Day
3  First Class
4     Same Day

[5 rows x 24 columns]

Total Rows: 5000

In [13]:
import os
print(os.getcwd())

C:\Users\acer\Desktop\DNPROJECT

In [51]:
# Display First 5 Records
df.head(30)

,Order_ID,Order_Date,Ship_Date,Year,Month,Quarter,Customer_ID,Customer_Name,Segment,Country,...,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Delivery_Days,Profit_Margin,Payment_Mode,Ship_Mode
0,ORD00001,2023-05-23,2023-05-29,2023,May,Q2,CUST2680,Shweta,Consumer,India,...,Sofa,Sofa,3870.49,4,5,1094.38,6,28.27,Net Banking,Same Day
1,ORD00002,2024-09-08,2024-09-09,2024,September,Q3,CUST4258,Shweta,Corporate,India,...,Table,Table,7373.54,4,20,1176.30,1,15.95,UPI,Same Day
2,ORD00003,2023-10-12,2023-10-14,2023,October,Q4,CUST4528,Vikas,Consumer,India,...,Table,Table,1728.98,7,10,7.95,2,0.46,Cash,Same Day
3,ORD00004,2024-07-03,2024-07-04,2024,July,Q3,CUST7202,Neha,Home Office,India,...,Keyboard,Keyboard,769.22,1,15,194.74,1,25.32,Credit Card,First Class
4,ORD00005,2023-10-24,2023-10-25,2023,October,Q4,CUST4815,Priya,Corporate,India,...,Notebook,Notebook,6090.93,1,5,1204.94,1,19.78,Credit Card,Same Day
5,ORD00006,2024-11-17,2024-11-20,2024,November,Q4,CUST2170,Simran,Home Office,India,...,Sofa,Sofa,401.73,6,5,116.29,3,28.95,UPI,Second Class
6,ORD00007,2024-12-02,2024-12-05,2024,December,Q4,CUST1917,Pooja,Consumer,India,...,Keyboard,Keyboard,8357.94,9,5,203.25,3,2.43,Credit Card,Same Day
7,ORD00008,2024-02-10,2024-02-16,2024,February,Q1,CUST8518,Ankit,Corporate,India,...,Sofa,Sofa,1981.88,4,15,28.13,6,1.42,UPI,Second Class
8,ORD00009,2024-01-06,2024-01-08,2024,January,Q1,CUST3267,Deepak,Corporate,India,...,Marker,Marker,3181.57,10,15,425.26,2,13.37,Cash,Standard Class
9,ORD00010,2023-03-07,2023-03-11,2023,March,Q1,CUST7253,Simran,Corporate,India,...,Pen,Pen,4433.06,7,20,230.21,4,5.19,Net Banking,First Class
10,ORD00011,2024-10-18,2024-10-21,2024,October,Q4,CUST2828,Anjali,Corporate,India,...,Notebook,Notebook,6196.16,9,10,-7.29,3,-0.12,UPI,Same Day
11,ORD00012,2024-10-02,2024-10-05,2024,October,Q4,CUST9318,Simran,Consumer,India,...,Pen,Pen,3063.02,9,0,239.61,3,7.82,UPI,First Class
12,ORD00013,2024-05-15,2024-05-16,2024,May,Q2,CUST2833,Nisha,Corporate,India,...,Notebook,Notebook,4669.49,10,10,1049.76,1,22.48,UPI,Standard Class
13,ORD00014,2024-06-29,2024-07-06,2024,June,Q2,CUST3061,Ankit,Home Office,India,...,Chair,Chair,2156.80,8,0,280.35,7,13.00,Debit Card,Second Class
14,ORD00015,2024-11-18,2024-11-24,2024,November,Q4,CUST7119,Arjun,Home Office,India,...,Table,Table,6005.66,5,15,-202.65,6,-3.37,Debit Card,Standard Class
15,ORD00016,2024-07-21,2024-07-23,2024,July,Q3,CUST4609,Rahul,Consumer,India,...,Sofa,Sofa,6153.94,1,20,59.59,2,0.97,Cash,Second Class
16,ORD00017,2023-10-13,2023-10-19,2023,October,Q4,CUST8954,Sneha,Home Office,India,...,Laptop,Laptop,837.51,9,5,236.27,6,28.21,UPI,Same Day
17,ORD00018,2024-11-05,2024-11-09,2024,November,Q4,CUST6805,Ritika,Corporate,India,...,Printer,Printer,9663.19,2,0,2250.93,4,23.29,Debit Card,Standard Class
18,ORD00019,2023-09-12,2023-09-14,2023,September,Q3,CUST4117,Shweta,Corporate,India,...,Bookcase,Bookcase,3185.21,6,0,-50.37,2,-1.58,UPI,Same Day
19,ORD00020,2024-07-17,2024-07-18,2024,July,Q3,CUST1829,Shweta,Consumer,India,...,Printer,Printer,6905.48,2,15,718.54,1,10.41,Cash,Second Class
20,ORD00021,2023-03-02,2023-03-04,2023,March,Q1,CUST7210,Rahul,Corporate,India,...,Mouse,Mouse,1395.97,4,15,172.14,2,12.33,Credit Card,Same Day
21,ORD00022,2023-10-31,2023-11-02,2023,October,Q4,CUST1959,Akash,Home Office,India,...,Marker,Marker,537.01,3,5,144.06,2,26.83,Net Banking,Standard Class
22,ORD00023,2024-05-29,2024-06-05,2024,May,Q2,CUST9702,Rohan,Consumer,India,...,Chair,Chair,2736.04,10,15,497.64,7,18.19,Net Banking,Standard Class
23,ORD00024,2023-05-03,2023-05-08,2023,May,Q2,CUST5034,Akash,Home Office,India,...,Notebook,Notebook,3254.77,4,15,429.71,5,13.20,Cash,Standard Class
24,ORD00025,2023-09-29,2023-10-03,2023,September,Q3,CUST3145,Anjali,Corporate,India,...,Printer,Printer,5557.76,6,5,81.69,4,1.47,Credit Card,Standard Class
25,ORD00026,2023-08-07,2023-08-12,2023,August,Q3,CUST5346,Ankit,Corporate,India,...,Notebook,Notebook,9701.93,2,20,2147.00,5,22.13,Cash,Second Class
26,ORD00027,2024-09-18,2024-09-25,2024,September,Q3,CUST9667,Rahul,Home Office,India,...,Bookcase,Bookcase,9407.09,9,10,2475.85,7,26.32,Net Banking,First Class
27,ORD00028,2024-07-20,2024-07-22,2024,July,Q3,CUST5463,Anjali,Home Office,India,...,Sofa,Sofa,6059.42,2,0,1652.14,2,27.27,UPI,First Class
28,ORD00029,2023-09-15,2023-09-22,2023,September,Q3,CUST1833,Neha,Home Office,India,...,Paper,Paper,1067.23,9,15,19.84,7,1.86,Debit Card,First Class
29,ORD00030,2024-03-28,2024-04-02,2024,March,Q1,CUST8008,Shweta,Consumer,India,...,Printer,Printer,643.23,5,5,41.08,5,6.39,Cash,Standard Class

In [15]:
# Display last 5 Records

df.tail()

,Order_ID,Order_Date,Ship_Date,Year,Month,Quarter,Customer_ID,Customer_Name,Segment,Country,...,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Delivery_Days,Profit_Margin,Payment_Mode,Ship_Mode
0,ORD05000,2023-07-10,2023-07-17,2023,July,Q3,CUST8657,Rahul,Home Office,India,...,Printer,Printer,4095.38,7,0,106.48,7,2.6,Debit Card,Same Day

In [52]:
# Check Dataset Shape

df.shape

(5000, 24)

In [53]:
# Display Column Names

df.columns

Index(['Order_ID', 'Order_Date', 'Ship_Date', 'Year', 'Month', 'Quarter',
       'Customer_ID', 'Customer_Name', 'Segment', 'Country', 'State', 'City',
       'Region', 'Category', 'Sub_Category', 'Product_Name', 'Sales',
       'Quantity', 'Discount', 'Profit', 'Delivery_Days', 'Profit_Margin',
       'Payment_Mode', 'Ship_Mode'],
      dtype='object')

In [54]:
# Check Data Types
df.dtypes

Order_ID          object
Order_Date        object
Ship_Date         object
Year               int64
Month             object
Quarter           object
Customer_ID       object
Customer_Name     object
Segment           object
Country           object
State             object
City              object
Region            object
Category          object
Sub_Category      object
Product_Name      object
Sales            float64
Quantity           int64
Discount           int64
Profit           float64
Delivery_Days      int64
Profit_Margin    float64
Payment_Mode      object
Ship_Mode         object
dtype: object

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       5000 non-null   object
 1   Order_Date     5000 non-null   object
 2   Ship_Date      5000 non-null   object
 3   Year           5000 non-null   int64
 4   Month          5000 non-null   object
 5   Quarter        5000 non-null   object
 6   Customer_ID    5000 non-null   object
 7   Customer_Name  5000 non-null   object
 8   Segment        5000 non-null   object
 9   Country        5000 non-null   object
 10  State          5000 non-null   object
 11  City           5000 non-null   object
 12  Region         5000 non-null   object
 13  Category       5000 non-null   object
 14  Sub_Category   5000 non-null   object
 15  Product_Name   5000 non-null   object
 16  Sales          5000 non-null   float64
 17  Quantity       5000 non-null   int64
 18  Discount       5000 non-null   int64
 19  Profit         5000 non-null   float64
 20  Delivery_Days  5000 non-null   int64
 21  Profit_Margin  5000 non-null   float64
 22  Payment_Mode   5000 non-null   object
 23  Ship_Mode      5000 non-null   object
dtypes: float64(3), int64(4), object(17)
memory usage: 937.6+ KB

In [56]:
# Check Missing Values
df.isnull().sum()

Order_ID         0
Order_Date       0
Ship_Date        0
Year             0
Month            0
Quarter          0
Customer_ID      0
Customer_Name    0
Segment          0
Country          0
State            0
City             0
Region           0
Category         0
Sub_Category     0
Product_Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Delivery_Days    0
Profit_Margin    0
Payment_Mode     0
Ship_Mode        0
dtype: int64

In [57]:
# Fill Missing Values
# Numeric Columns
df["Sales"] = df["Sales"].fillna(df["Sales"].mean())
df["Profit"] = df["Profit"].fillna(df["Profit"].mean())

In [58]:
#Text Columns
df["Customer_Name"] = df["Customer_Name"].fillna("Unknown")

In [59]:
#Check Duplicate Records
df.duplicated().sum()

np.int64(0)

In [60]:
# Check Unique Values
#df["Category"].unique()

#OR

df["State"].unique()

array(['Madhya Pradesh', 'Delhi', 'Gujarat', 'Maharashtra', 'Karnataka',
       'Bihar'], dtype=object)

In [61]:
#Convert Date Columns

df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Ship_Date"] = pd.to_datetime(df["Ship_Date"])

In [81]:
#Extract Year
df["Year"] = df["Order_Date"].dt.year

In [82]:
#Extract Quarter
df["Quarter"] = df["Order_Date"].dt.quarter

In [66]:
df.head()

,Order_ID,Order_Date,Ship_Date,Year,Month,Quarter,Customer_ID,Customer_Name,Segment,Country,...,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Delivery_Days,Profit_Margin,Payment_Mode,Ship_Mode
0,ORD00001,2023-05-23,2023-05-29,2023,May,2,CUST2680,Shweta,Consumer,India,...,Sofa,Sofa,3870.49,4,5,1094.38,6,28.274973,Net Banking,Same Day
1,ORD00002,2024-09-08,2024-09-09,2024,September,3,CUST4258,Shweta,Corporate,India,...,Table,Table,7373.54,4,20,1176.30,1,15.952989,UPI,Same Day
2,ORD00003,2023-10-12,2023-10-14,2023,October,4,CUST4528,Vikas,Consumer,India,...,Table,Table,1728.98,7,10,7.95,2,0.459809,Cash,Same Day
3,ORD00004,2024-07-03,2024-07-04,2024,July,3,CUST7202,Neha,Home Office,India,...,Keyboard,Keyboard,769.22,1,15,194.74,1,25.316554,Credit Card,First Class
4,ORD00005,2023-10-24,2023-10-25,2023,October,4,CUST4815,Priya,Corporate,India,...,Notebook,Notebook,6090.93,1,5,1204.94,1,19.782529,Credit Card,Same Day

In [67]:
# Check Outliers
df.describe()

,Order_Date,Ship_Date,Year,Quarter,Sales,Quantity,Discount,Profit,Delivery_Days,Profit_Margin
count,5000,5000,5000.000000,5000.000000,5000.000000,5000.0000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2024-01-02 11:15:38.880000256,2024-01-06 10:27:33.119999744,2023.506400,2.502400,5031.798254,5.4282,10.085000,613.866350,3.966600,12.334746
min,2023-01-01 00:00:00,2023-01-03 00:00:00,2023.000000,1.000000,200.110000,1.0000,0.000000,-459.780000,1.000000,-4.998749
25%,2023-07-08 00:00:00,2023-07-12 18:00:00,2023.000000,1.000000,2608.060000,3.0000,5.000000,97.735000,2.000000,3.641898
50%,2024-01-06 12:00:00,2024-01-10 00:00:00,2024.000000,3.000000,4999.110000,5.0000,10.000000,420.700000,4.000000,12.321670
75%,2024-06-30 00:00:00,2024-07-04 00:00:00,2024.000000,4.000000,7426.452500,8.0000,15.000000,1005.307500,6.000000,20.979089
max,2024-12-31 00:00:00,2025-01-07 00:00:00,2024.000000,4.000000,9994.250000,10.0000,20.000000,2877.670000,7.000000,29.990094
std,NaN,NaN,0.500009,1.126875,2812.507824,2.9268,7.137784,667.084347,2.000471,10.090241

In [68]:
# Filter High Sales
high_sales = df[df["Sales"] > 5000]

In [69]:
# Category-wise Sales
category_sales = df.groupby("Category")["Sales"].sum()
print(category_sales)

Category
Furniture          8601874.43
Office Supplies    8062068.91
Technology         8495047.93
Name: Sales, dtype: float64

In [70]:
# State-wise Profit
state_profit = df.groupby("State")["Profit"].sum()
print(state_profit)

State
Bihar             499382.21
Delhi             513658.66
Gujarat           507172.09
Karnataka         523488.25
Madhya Pradesh    508590.59
Maharashtra       517039.95
Name: Profit, dtype: float64

In [71]:
# Top 10 Customers
top_customers=(
      df.groupby("Customer_Name")["Sales"].sum().sort_values(ascending=False).head(10)
)
print(top_customers)

Customer_Name
Akash     1416907.76
Riya      1397528.58
Ankit     1380096.65
Ritika    1360792.52
Sneha     1353264.17
Arjun     1331909.61
Neha      1330987.18
Anjali    1329465.22
Rahul     1300651.57
Pooja     1241863.29
Name: Sales, dtype: float64

In [72]:
df.head()

,Order_ID,Order_Date,Ship_Date,Year,Month,Quarter,Customer_ID,Customer_Name,Segment,Country,...,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Delivery_Days,Profit_Margin,Payment_Mode,Ship_Mode
0,ORD00001,2023-05-23,2023-05-29,2023,May,2,CUST2680,Shweta,Consumer,India,...,Sofa,Sofa,3870.49,4,5,1094.38,6,28.274973,Net Banking,Same Day
1,ORD00002,2024-09-08,2024-09-09,2024,September,3,CUST4258,Shweta,Corporate,India,...,Table,Table,7373.54,4,20,1176.30,1,15.952989,UPI,Same Day
2,ORD00003,2023-10-12,2023-10-14,2023,October,4,CUST4528,Vikas,Consumer,India,...,Table,Table,1728.98,7,10,7.95,2,0.459809,Cash,Same Day
3,ORD00004,2024-07-03,2024-07-04,2024,July,3,CUST7202,Neha,Home Office,India,...,Keyboard,Keyboard,769.22,1,15,194.74,1,25.316554,Credit Card,First Class
4,ORD00005,2023-10-24,2023-10-25,2023,October,4,CUST4815,Priya,Corporate,India,...,Notebook,Notebook,6090.93,1,5,1204.94,1,19.782529,Credit Card,Same Day

In [73]:
city_sales=(
   df.groupby("City")["Sales"].sum()
)
print(city_sales)

City
Ahmedabad    2373741.12
Bengaluru    2165889.46
Bhopal       2169561.46
Darbhanga    2098456.53
Indore       1915470.28
Mumbai       1534513.12
Mysuru       2073764.93
Nagpur       1301779.69
New Delhi    4129069.06
Patna        2000161.73
Pune         1445661.64
Surat        1950922.25
Name: Sales, dtype: float64

In [74]:
#Total Sales
total_sales=df["Sales"].sum()
print(total_sales)

25158991.269999996

In [75]:
# Average Sales
average_sales=df["Sales"].mean()
print(average_sales)

5031.798253999999

In [84]:
df.to_csv("sales_clean1.csv",index=False)
print("sales_clean.csv created successfully!")

sales_clean.csv created successfully!

In [ ]:

print(os.listdir())